apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: logstash-git
  labels:
    app.kubernetes.io/instance: logstash-git
    pipeline.openshift.io/strategy: docker
    pipeline.openshift.io/type: openshift
spec:
  params:
    - default: logstash-git
      name: APP_NAME
      type: string
    - default: 'https://github.com/bcgov/Enterprise-Connector'
      name: GIT_REPO
      type: string
    - default: master
      name: GIT_REVISION
      type: string
    - default: 'xxx'
      name: IMAGE_NAME
      type: string
    - default: logstash
      name: PATH_CONTEXT
      type: string
  tasks:
    - name: fetch-repository
      params:
        - name: url
          value: $(params.GIT_REPO)
        - name: revision
          value: $(params.GIT_REVISION)
        - name: subdirectory
          value: ''
        - name: deleteExisting
          value: 'true'
      taskRef:
        kind: ClusterTask
        name: git-clone
      workspaces:
        - name: output
          workspace: workspace
    - name: build
      params:
        - name: IMAGE
          value: $(params.IMAGE_NAME)
        - name: TLSVERIFY
          value: 'false'
        - name: CONTEXT
          value: $(params.PATH_CONTEXT)
      runAfter:
        - fetch-repository
      taskRef:
        kind: Task
        name: buildah-large-memory
      workspaces:
        - name: source
          workspace: workspace
    - name: deploy
        - name: SCRIPT
          value: oc rollout status dc/$(params.APP_NAME)
      runAfter:
        - build
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
    - name: workspace
